logging:
  level:
    org.springframework.web: INFO
    com.etna.gpe.mycloseshop.ms_payment_api: INFO
    com.etna.gpe.mycloseshop.security_api: INFO
    slf4j: INFO
    org.springframework.security: INFO

rabbitmq:
  exchange:
  queue:
  routing-keys:

server:
  port: ${SPRING_APP_URL:8087}
  servlet:
    context-path: /api/ms-payment-api
spring:
  application:
    name: 'ms-payment-api'
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/db-ms-payment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    discovery:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  rabbitmq:
    port: ${SPRING_RABBITMQ_PORT:5672}
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  main:
    allow-bean-definition-overriding: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html